import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width,initial-scale=1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between  gap-large relative ">
        <Header bgColor="bg-black" height="h-[150px]"></Header>
        {children}
        <Footer
          height="h-[100px]"
          bgColor="bg-black"
          margin="-mt-large"
          flex="flex items-center justify-center"
        ></Footer>
      </body>
    </html>
  );
}
